CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  body VARCHAR NOT NULL,
  date TIMESTAMP NOT NULL,
  url VARCHAR NOT NULL,
  image VARCHAR NOT NULL,

  tour_id INTEGER REFERENCES tours(id)
)
