services:
  database:
    image: postgres:16.3-alpine
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=LOCAL
      - POSTGRES_USER=admin
      - POSTGRES_DB=otl
  backend:
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app
    command: sh -c "cargo-watch -x run"
