services:
  database:
    image: postgres:16.3-alpine
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=LOCAL
      - POSTGRES_USER=admin
      - POSTGRES_DB=otl
  backend:
    build: ./backend
    entrypoint: /app/target/release/main
    ports:
      - 8000:8000
    # for local dev
    # volumes:
    #   - ./backend/:/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
