services:
  database:
    image: postgres:16.3-alpine
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=LOCAL
      - POSTGRES_USER=admin
      - POSTGRES_DB=otl
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: ./prod.Dockerfile
    entrypoint: /app/main
    ports:
      - 8000:8000
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: always
