services:
  otl-database:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=LOCAL
      - POSTGRES_USER=admin
      - POSTGRES_DB=otl
  # web:
  #   container_name: web
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:./frontend
